name = "gado7h/bedrock"
version = "1.1.1"
description = "A lightweight Unix-like kernel for Roblox OS emulation"
authors = ["gado7h"]
repository = "https://github.com/gado7h/bedrock"
license = "MIT"
includes = ["src", "pesde.toml", "README.md", "CHANGELOG.md", "docs"]

[indices]
default = "https://github.com/pesde-pkg/index.git"

[target]
environment = "roblox"
lib = "src/Kernel/init.luau"
build_files = ["src"]
